# Generated by Django 5.1.5 on 2025-01-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('food_type', models.CharField(max_length=100)),
                ('food_price', models.IntegerField()),
                ('descripetion', models.TextField()),
            ],
        ),
    ]
